"""
Discovery job — Milestone 16.7.

The reusable core of `vault:discover-providers`: query every registered provider's live
`/models`, build a PROPOSED registry (chat models capability-tagged + a second table of
specialized/non-chat models), and write it to `AI/System/Provider-Registry-proposed.md`
between the tracker's BEGIN/END markers. It never commits — `vault:update-providers
apply` does that (propose/commit). Shared by the terminal command and the weekly
scheduler so both produce an identical, review-first proposal.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger("assistant")


def run_discovery_proposal(vault_path, config: dict, list_fn=None) -> tuple[bool, str]:
    """Build and write the discovery proposal. Returns (ok, message).

    `list_fn` is injectable for tests (defaults to the live /models query). Writes
    nothing and returns (False, reason) if there is no vault or no providers."""
    from assistant_core.providers.model_discovery import discover_models
    from assistant_core.providers.registry_loader import RegistryLoader
    from assistant_core.providers.registry_proposer import build_proposed_registry
    from assistant_core.tools.provider_tracker import PROPOSED_REL, BEGIN_MARK, END_MARK

    if not vault_path:
        return False, "no vault_path"

    reg_path = Path(vault_path) / "AI" / "System" / "Provider-Registry.md"
    specs = RegistryLoader(reg_path).load() if reg_path.exists() else []
    providers: dict[str, str] = {}
    base_urls: dict[str, str] = {}
    for s in specs:
        providers.setdefault(s.provider, s.base_url)
        base_urls.setdefault(s.provider, s.base_url)
    if not providers:
        return False, "no providers in the registry yet"

    disc = discover_models(providers, config, list_fn=list_fn)
    registry_md = build_proposed_registry(disc, specs, base_urls)
    note = ("# Provider Registry — discovery proposal\n\n"
            "Generated by provider discovery. Review, then run "
            "`vault:update-providers apply` to commit (or delete this file to reject).\n\n"
            f"{BEGIN_MARK}\n{registry_md}\n{END_MARK}\n")

    out_path = Path(vault_path) / PROPOSED_REL
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(note, encoding="utf-8")

    kept = sum(len(d["models"]) for d in disc.values() if not d.get("error"))
    errs = [p for p, d in disc.items() if d.get("error")]
    msg = f"{kept} model(s) discovered → {PROPOSED_REL}"
    if errs:
        msg += f" ({len(errs)} provider error(s): {', '.join(errs)})"
    logger.info(f"[Discovery] {msg}")
    return True, msg
