"""
Daily Briefing — Milestone 34 (proactive, read-only).

Each morning the service assembles a short briefing of what's happening in the vault —
notes changed since yesterday, flashcards due today, and anything waiting for the user's
approval — plus a 2-3 sentence suggested focus. Written to `AI/Briefings/YYYY-MM-DD.md`.

**Read-only: it never modifies a note.** Deterministic apart from the optional focus line
(one short, low-temperature, grounded model call — skipped if no router).
"""

import logging
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger("assistant")

BRIEFINGS_DIR = "AI/Briefings"
_SKIP_PREFIXES = ("AI/System", "AI/Memory/Episodes", "AI/Briefings", "AI/Chat",
                  ".trash", ".obsidian")


def _rel(vault: Path, p: Path) -> str:
    return str(p.relative_to(vault)).replace("\\", "/")


def recent_notes(vault, hours: int = 24, now: datetime | None = None) -> list[str]:
    """Vault notes modified within the last `hours` (excludes system/derived folders)."""
    vault = Path(vault)
    cutoff = ((now or datetime.now()) - timedelta(hours=hours)).timestamp()
    out: list[str] = []
    for p in vault.rglob("*.md"):
        rel = _rel(vault, p)
        if any(rel.startswith(s) for s in _SKIP_PREFIXES):
            continue
        try:
            if p.stat().st_mtime >= cutoff:
                out.append(rel)
        except OSError:
            continue
    return sorted(out)


def pending_proposals(vault) -> list[str]:
    """Proposals awaiting the user's approval (consolidation facts + auto-organize)."""
    vault = Path(vault)
    items: list[str] = []
    for d in ("AI/Memory/proposed", "AI/Proposed"):
        dd = vault / d
        if dd.exists():
            items += [_rel(vault, f) for f in dd.glob("*.md")]
    return sorted(items)


def _focus_line(router, changed: list[str], due_n: int, private: bool = False) -> str:
    if router is None or not getattr(router, "available_providers", None):
        return ""
    from assistant_core.providers.base_provider import Message
    titles = ", ".join(Path(c).stem for c in changed[:12]) or "(no recent changes)"
    prompt = (f"In 2-3 sentences, suggest a focus for today. Recently touched notes: {titles}. "
              f"{due_n} flashcard(s) due. Be concrete and brief; do not invent notes or facts.")
    try:
        reply, _ = router.generate([Message(role="user", content=prompt)],
                                   task="qa", private=private, allow_webui=False)
        return (reply or "").strip()
    except Exception as exc:
        logger.info(f"[Briefing] focus line skipped: {exc}")
        return ""


def build_briefing(vault, config: dict | None = None, rag=None, router=None,
                   now: datetime | None = None) -> str:
    now = now or datetime.now()
    date = now.strftime("%Y-%m-%d")
    changed = recent_notes(vault, now=now)
    try:
        from assistant_core.study.cards import due_cards
        due = due_cards(vault)
    except Exception:
        due = []
    pending = pending_proposals(vault)

    lines = [f"# Daily Briefing — {date}", ""]

    focus = _focus_line(router, changed, len(due))
    if focus:
        lines += ["## Focus", "", focus, ""]

    lines.append(f"## Recently changed ({len(changed)})")
    lines += ([f"- [[{Path(c).stem}]]" for c in changed[:15]]
              + ([f"- …and {len(changed) - 15} more"] if len(changed) > 15 else [])
              if changed else ["- (nothing changed in the last day)"])
    lines.append("")

    lines.append(f"## Flashcards due ({len(due)})")
    lines += ([f"- {c.get('q', '')[:80]}  _(from {c.get('source', '?')})_" for c in due[:8]]
              + (["- …"] if len(due) > 8 else [])
              if due else ["- None due 🎉"])
    lines.append("")

    lines.append(f"## Awaiting your approval ({len(pending)})")
    lines += ([f"- {p}" for p in pending] if pending else ["- Nothing pending"])
    lines.append("")
    lines.append("---\n*Generated by Loremaster — read-only briefing.*")
    return "\n".join(lines)


def write_briefing(vault, config: dict | None = None, rag=None, router=None,
                   now: datetime | None = None) -> str:
    """Build + save today's briefing. Returns the vault-relative path."""
    now = now or datetime.now()
    md = build_briefing(vault, config, rag, router, now=now)
    rel = f"{BRIEFINGS_DIR}/{now.strftime('%Y-%m-%d')}.md"
    dest = Path(vault) / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(md, encoding="utf-8")
    logger.info(f"[Briefing] wrote {rel}")
    return rel
